version: '3.7'

services:
  trackit-wrapper:
    container_name: trackit-wrapper
    image: 'ghcr.io/garrettpfoy/trackit-wrapper:main'
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 3006:3006 #Needs to match env var HOST_PORT
  watchtower:
    container_name: trackit-watchtower
    image: 'containrrr/watchtower'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    command: [ "--interval", "30", "trackit-wrapper"]