version: '3.7'

services:
  trackit-wrapper:
    image: 'ghcr.io/garrettpfoy/trackit-wrapper:main'
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 3006:3006
  watchtower:
    image: 'containrrr/watchtower'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    command: --interval 30