name: Validate Commit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.15'

      - name: Build
        run: go build -v ./...

      - name: Scan
        uses: securego/gosec@master
        with:
          args: ./...

      - name: Test
        run: go test -v ./...